#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("create_pivot_list() works", {

  expect_error(
    kwb.umberto:::create_pivot_list()
    # argument "pivot_data" is missing, with no default
  )

})

