#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("write_xlsx() works", {

  expect_error(
    kwb.lca:::write_xlsx()
    # argument "data_pivot_list" is missing, with no default
  )

})

