#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("group_data() works", {

  expect_error(
    kwb.umberto:::group_data()
    # argument "raw_data" is missing, with no default
  )

})

