#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2022-11-18 13:49:45.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("group_data() works", {

  expect_error(
    kwb.umberto:::group_data()
    # argument "raw_data" is missing, with no default
  )

})

