#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("pivot_data() works", {

  expect_error(
    kwb.lca:::pivot_data()
    # argument "rawdata_grouped" is missing, with no default
  )

})

