#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("import_rawdata() works", {

  expect_error(
    kwb.lca:::import_rawdata()
    # argument "csv_dir" is missing, with no default
  )

})

